# Generated by Django 6.0.2 on 2026-03-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="state",
            field=models.CharField(max_length=20),
        ),
    ]
