# Generated by Django 6.0.2 on 2026-02-26 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="photo",
            field=models.ImageField(default="drop-bear.png", upload_to="gallery"),
        ),
    ]
